### ISSUE TITLE
Option to rebuild uce?

### ISSUE THREAD

**Issue by jdeath** [jimnarey/alu_auto_builder#4]
Is there an option to just rebuild UCEs? Point to a directory and rebuild/replace, keeping save partition, art, etc?

**Comment by dudemo** [comment]
There isn't. I can't see a reason to rebuild a UCE without changing anything. Even to convert the old UCE files to work on newer firmware, you are in fact changing something (permissions). I suppose it could be done, but to what advantage?

**Comment by jimnarey** [comment]
There isn't such an option at present. It's probably not a lot of work to implement but it would be helpful to know what the use case is, as there might be a better way of achieving whatever it is.

**Comment by jdeath** [comment]
Use case is my UCE’s are setup exactly how I like. File names are what I need to match my playlists, coinops art, and custom bit pixel marquees. My setup is custom with uces of different consoles in different directories, with a mix of .so which have been predetermined to work. I just want them remade to support new firmware. So an automated directory traversal, unzip the files, then repackage uce with same file name would be awesome! Is there another way to do this? I could probably do it in python if the new uce tool that can be called easily via command line. 

edit: Ok, this wasn't that hard. I am using windows linux subsystem.

1. Change the mksquashfs flags in line 25 of the original [build_sq_cartridge_pack.sh](https://github.com/FalkensMaze1983/ultimate_addon/blob/master/build_sq_cartridge_pack.sh)  to as suggested in the latest commit of https://github.com/jimnarey/alu_auto_builder/commit/7df5f37436c5483729bbc3e65738b37836b7be4a#diff-dd7afbd479351771624f2fe3cbd58deb73477cb1a68d05550d16b174ea2d209a: 
```mksquashfs $1 $cart_tmp_file -comp gzip -b 262144 -force-uid 12 -force-gid 12 -noappend -nopad```
3. Then run in a loop (I used python) over all your UCEs: unsquashfs to extract the uce, then use your fixed build_sq_cartridge_pack.sh to rebuild.

A version in python is below. My UCEs are in separate directories under the root. Hope this helps. Much easier than building from scratch if you like your collection.  Just copy the uce's back and rerun addonx tool. Works on the old firmware, I haven't upgraded yet, but I am ready!

```
#!/usr/bin/python3

import os
import subprocess
import shlex
rootdir = '/mnt/c/Users/me/Downloads/ALU Roms - Working/'
subdirs = ['arcade','Atari 2600','Daphne','Gameboy','Intellivision','NEOGEO','Nintendo','ScummVM','Sega Genesis','SNES']

new_rootdir = './NewDir/'

subprocess.call(['mkdir',new_rootdir])

for subdir in subdirs:
    print(subdir)
    mypath = rootdir + subdir
    subprocess.call(['mkdir',new_rootdir + subdir])
    filenames = next(os.walk(mypath), (None, None, []))[2]
    for file in filenames:
      
        if file[-3:].lower() == "uce":      
            
            oldFileName = rootdir + subdir + "/" + file           
            newFileName = new_rootdir + subdir + "/" + file
                       
            subprocess.call(['rm','-rf','squashfs-root/'])
            subprocess.call(['unsquashfs', oldFileName])
            subprocess.call(['./build_sq_cartridge_pack_fixed.sh', 'squashfs-root/', newFileName] )
        

```

**Comment by jimnarey** [comment]
Thank you! I'll see if I can incorporate this into the tool.

I like your one-liner for os.walk().

There are a couple of things where Python includes some built-in help:

- os.path.join() for concating paths. Works cross platform and handles slashes automatically.
- os.path.splitext() for getting a file extension.
- the os and shutil modules have functions for removing dirs and populated dirs respectively.

**Comment by dudemo** [comment]
I'd just been doing this in my work folder with UCE's in it.

First, add 7-Zip to path (either Windows or Linux). Second, in a command prompt/shell, type: 

`7z x *.UCE -o*`

That will extract everything recursively. Now just run "Recipe's to UCE" on the folder.

**Comment by jdeath** [comment]
> `7z x *.UCE -o*`
Super elegant. That would have saved me some time!

> I like your one-liner for os.walk().
Found it on the internet, not my doing at all. Thanks for python tips, I code by googling!
